//! Cross-language test vector replay harness.
//!
//! Loads JSON fixtures generated by `test-vectors/scripts/*.py` against the
//! Syndace reference implementations and replays them against Rust crates.
//! Goal: byte-for-byte identical output for every fixture in every primitive.

use anyhow::{anyhow, Context, Result};
use serde::Deserialize;
use std::path::{Path, PathBuf};

#[derive(Debug, Deserialize)]
pub struct Fixture<C> {
    pub source: String,
    pub algorithm: String,
    #[serde(default)]
    pub note: String,
    pub cases: Vec<C>,
}

pub fn fixtures_dir() -> PathBuf {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest
        .ancestors()
        .find_map(|p| {
            let candidate = p.join("test-vectors").join("fixtures");
            candidate.is_dir().then_some(candidate)
        })
        .expect("test-vectors/fixtures not found relative to crate")
}

pub fn load_fixture<C: for<'de> Deserialize<'de>>(name: &str) -> Result<Fixture<C>> {
    let path = fixtures_dir().join(name);
    let bytes =
        std::fs::read(&path).with_context(|| format!("read fixture {}", path.display()))?;
    serde_json::from_slice(&bytes).with_context(|| format!("parse fixture {}", path.display()))
}

pub fn hex_decode(s: &str) -> Result<Vec<u8>> {
    hex::decode(s).map_err(|e| anyhow!("hex decode: {e}"))
}
